### ISSUE TITLE
Oauth examples not working

### ISSUE THREAD

**Issue by gnumdk** [mozilla/PyFxA#52]
When I try examples from README, I get:

>>> raw_resp = requests.get('https://profile.accounts.firefox.com/v1/profile',
...                         auth=FxABearerTokenAuth(email, password,
...                                                 ['profile'], "browser"))
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 543, in prepare_auth
    r = auth(self)
  File "/usr/lib/python3.6/site-packages/fxa/plugins/requests.py", line 146, in __call__
    oauth_server_url=self.oauth_server_url)
  File "/usr/lib/python3.6/site-packages/fxa/tools/bearer.py", line 42, in get_bearer_token
    client_id)
  File "/usr/lib/python3.6/site-packages/fxa/oauth.py", line 154, in authorize_token
    resp = self.apiclient.post(url, body)
  File "/usr/lib/python3.6/site-packages/fxa/_utils.py", line 300, in post
    return self.request("POST", url, json, **kwds)
  File "/usr/lib/python3.6/site-packages/fxa/_utils.py", line 286, in request
    raise fxa.errors.ClientError(body)
fxa.errors.ClientError: Invalid request parameter

**Comment by vbudhram** [comment]
@gnumdk What is the code line you are trying to run? It is a little hard to make it out in the stack.

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by rfk** [comment]
@Natim the traceback here suggests an issue with the `FxABearerTokenAuth` plugin, can you please take a look and see if you can see what's going wrong?

**Comment by Natim** [comment]
Did the profile API change since we build the plugin?

**Comment by rfk** [comment]
I'm not aware of any changes in the API.

**Comment by rfk** [comment]
> FxABearerTokenAuth(email, password, ['profile'], "browser")

Oh wait, I see what's going on here.  You need an actual oauth client ID to use in this call, not the string "browser".  You can try using "5882386c6d801776" which is the oauth client ID of desktop Firefox.

**Comment by Natim** [comment]
Thanks @rfk for finding out the issue. @gnumdk can you confirm that it fixes your issue?

**Comment by gnumdk** [comment]
Yes, thanks.
