### ISSUE TITLE
client.login does not work with accounts.firefox.com

### ISSUE THREAD

**Issue by csabahenk** [mozilla/PyFxA#82]
Trying to log in to _accounts.firefox.com_ based on the example given in the README.

```
>>> fxa.__version__
'0.7.4'
>>> from fxa.core import Client as FxAClient
>>> sess=FxAClient("https://api.accounts.firefox.com").login(email, passw)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/csaba/python/src/PyFxA/fxa/core.py", line 93, in login
    resp = self.apiclient.post(url, body)
  File "/home/csaba/python/src/PyFxA/fxa/_utils.py", line 335, in post
    raise fxa.errors.OutOfProtocolError(msg.format(resp.status_code))
  File "/home/csaba/python/src/PyFxA/fxa/_utils.py", line 321, in request
    msg = "API responded with non-integer timestamp: {0}"
fxa.errors.ClientError: The request was blocked for security reasons
```

However, if we patch the login method to consume further options like this:

```diff
diff --git a/fxa/core.py b/fxa/core.py
index 6706cdf..7b2a164 100644
--- a/fxa/core.py
+++ b/fxa/core.py
@@ -74,7 +74,7 @@ class Client(object):
             auth_timestamp=resp["authAt"],
         )
 
-    def login(self, email, password=None, stretchpwd=None, keys=False, unblock_code=None):
+    def login(self, email, password=None, stretchpwd=None, keys=False, unblock_code=None, **kw):
         stretchpwd = self._get_stretched_password(email, password, stretchpwd)
         body = {
             "email": email,
@@ -87,6 +87,9 @@ class Client(object):
         if unblock_code:
             body["unblockCode"] = unblock_code
 
+        for k,v in kw.items():
+            body[k] = v
+
         resp = self.apiclient.post(url, body)
         # XXX TODO: somehow sanity-check the schema on this endpoint
         return Session(
```

then login can be got to work with a suitable invocation:

```
>>> sess=FxAClient("https://api.accounts.firefox.com").login(email, passw, reason="login", verificationMethod="email-captcha")
>>> sess
<fxa.core.Session object at 0x7f5079b96280>
```

This is a recent change on the server side; in 2020 May `email` and `passw` was sufficient to log in.

**Comment by rfk** [comment]
Thanks for investigating this! I won't have bandwidth to take a look until next week, but based on your findings above, hopefully it's a smallish fix.
